Fix syntax error in fis yml

diff --git a/.github/workflows/installations.yml b/.github/workflows/installations.yml
--- a/.github/workflows/installations.yml
+++ b/.github/workflows/installations.yml
@@ -41,40 +41,40 @@ jobs:
         testapp_dir: quickstart-ios/build-for-testing
         test_type: "xctest"
 
-  installations-cron-only:
-    if: github.event_name == 'schedule' && github.repository == 'Firebase/firebase-ios-sdk'
-
-    runs-on: macos-14
-    env:
-      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
-      FIR_IID_INTEGRATION_TESTS_REQUIRED: ${{ secrets.GHASecretsGPGPassphrase1 }}
-    strategy:
-      matrix:
-        target: [ios, tvos, macos]
-        flags: [
-          '--use-static-frameworks'
-        ]
-    needs: pod-lib-lint
-    steps:
-    - uses: actions/checkout@v4
-    - uses: ruby/setup-ruby@v1
-    - name: Setup Bundler
-      run: scripts/setup_bundler.sh
-    - name: Configure test keychain
-      run: scripts/configure_test_keychain.sh
-    - name: Install GoogleService-Info.plist
-      run: |
-        mkdir -p FirebaseInstallations/Source/Tests/Resources
-        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/Installations/GoogleService-Info.plist.gpg \
-          FirebaseInstallations/Source/Tests/Resources/GoogleService-Info.plist "$plist_secret"
-    - name: Get boolean for secrets available
-      id: secrets
-      run: echo "::set-output name=val::$([[ -z $plist_secret ]] && echo "0" || echo "1")"
-    - name: PodLibLint Installations Cron
-      run: |
-       export FIS_INTEGRATION_TESTS_REQUIRED=${{ steps.secrets.outputs.val }}
-       scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseInstallations.podspec \
-         --platforms=${{ matrix.target }} ${{ matrix.flags }} \
+#  installations-cron-only:
+#    if: github.event_name == 'schedule' && github.repository == 'Firebase/firebase-ios-sdk'
+#
+#    runs-on: macos-14
+#    env:
+#      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
+#      FIR_IID_INTEGRATION_TESTS_REQUIRED: ${{ secrets.GHASecretsGPGPassphrase1 }}
+#    strategy:
+#      matrix:
+#        target: [ios, tvos, macos]
+#        flags: [
+#          '--use-static-frameworks'
+#        ]
+#    needs: pod-lib-lint
+#    steps:
+#    - uses: actions/checkout@v4
+#    - uses: ruby/setup-ruby@v1
+#    - name: Setup Bundler
+#      run: scripts/setup_bundler.sh
+#    - name: Configure test keychain
+#      run: scripts/configure_test_keychain.sh
+#    - name: Install GoogleService-Info.plist
+#      run: |
+#        mkdir -p FirebaseInstallations/Source/Tests/Resources
+#        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/Installations/GoogleService-Info.plist.gpg \
+#          FirebaseInstallations/Source/Tests/Resources/GoogleService-Info.plist "$plist_secret"
+#    - name: Get boolean for secrets available
+#      id: secrets
+#      run: echo "::set-output name=val::$([[ -z $plist_secret ]] && echo "0" || echo "1")"
+#    - name: PodLibLint Installations Cron
+#      run: |
+#       export FIS_INTEGRATION_TESTS_REQUIRED=${{ steps.secrets.outputs.val }}
+#       scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseInstallations.podspec \
+#         --platforms=${{ matrix.target }} ${{ matrix.flags }} \
 
 #  pod-lib-lint:
 #    # Don't run on private repo unless it is a PR.
