work

diff --git a/.github/workflows/zip.yml b/.github/workflows/zip.yml
--- a/.github/workflows/zip.yml
+++ b/.github/workflows/zip.yml
@@ -140,8 +140,19 @@ jobs:
         # name of.
         path: zip_output_dir
 
+  packaging_done:
+    runs-on: ubuntu-latest
+    needs: [package-head]
+    if: always()
+    steps:
+      - name: Check packaging result
+        if: ${{ needs.package-head.result == 'failure' }}
+        run: |
+          echo "Packaging failed. Aborting."
+          exit 1
+
   check_framework_firestore_symbols:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       FIREBASECI_USE_LATEST_GOOGLEAPPMEASUREMENT: 1
@@ -173,7 +184,7 @@ jobs:
             "${HOME}"/ios_frameworks/Firebase/FirebaseFirestore/FirebaseFirestoreInternal.xcframework
 
   quickstart_framework_abtesting:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -226,7 +237,7 @@ jobs:
     #     path: quickstart-ios/
 
   quickstart_framework_auth:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -276,7 +287,7 @@ jobs:
           !quickstart-ios/**/GoogleService-Info.plist
 
   quickstart_framework_config:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -325,7 +336,7 @@ jobs:
         path: quickstart-ios/
 
   quickstart_framework_crashlytics:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -386,17 +397,16 @@ jobs:
     #   env:
     #     LEGACY: true
     #   run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart_framework.sh "${SDK}" swift)
-    - name: Remove data before upload
-      if: always()
-      run: scripts/remove_data.sh crashlytics
     - uses: actions/upload-artifact@v4
       if: failure()
       with:
         name: quickstart_artifacts_crashlytics
-        path: quickstart-ios/
+        path: |
+          quickstart-ios/
+          !quickstart-ios/**/GoogleService-Info.plist
 
   quickstart_framework_database:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -438,17 +448,16 @@ jobs:
         quickstart-ios/database/GoogleService-Info.plist "$plist_secret"
     - name: Test Quickstart
       run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart_framework.sh "${SDK}")
-    - name: Remove data before upload
-      if: always()
-      run: scripts/remove_data.sh database
-    # - uses: actions/upload-artifact@v4
-    #   if: failure()
-    #   with:
-    #     name: quickstart_artifacts database
-    #     path: quickstart-ios/
+    - uses: actions/upload-artifact@v4
+      if: failure()
+      with:
+        name: quickstart_artifacts_database
+        path: |
+          quickstart-ios/
+          !quickstart-ios/**/GoogleService-Info.plist
 
   quickstart_framework_firestore:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -498,14 +507,14 @@ jobs:
     - name: Remove data before upload and zip directory to reduce upload size.
       if: always()
       run: scripts/remove_data.sh firestore; zip -r --symlinks quickstart_artifacts_firestore.zip quickstart-ios/
-    # - uses: actions/upload-artifact@v4
-    #   if: failure()
-    #   with:
-    #     name: quickstart_artifacts_firestore_${{ matrix.artifact }}_${{ matrix.build-env.os }}
-    #     path: quickstart_artifacts_firestore.zip
+    - uses: actions/upload-artifact@v4
+      if: failure()
+      with:
+        name: quickstart_artifacts_firestore_${{ matrix.artifact }}_${{ matrix.build-env.os }}
+        path: quickstart_artifacts_firestore.zip
 
   quickstart_framework_inappmessaging:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -548,17 +557,16 @@ jobs:
       run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart_framework.sh "${SDK}")
     - name: Test Swift Quickstart
       run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart_framework.sh "${SDK}" swift)
-    - name: Remove data before upload
-      if: always()
-      run: scripts/remove_data.sh inappmessaging
-    # - uses: actions/upload-artifact@v4
-    #   if: failure()
-    #   with:
-    #     name: quickstart_artifacts_inappmessaging
-    #     path: quickstart-ios/
+    - uses: actions/upload-artifact@v4
+      if: failure()
+      with:
+        name: quickstart_artifacts_inappmessaging
+        path: |
+          quickstart-ios/
+          !quickstart-ios/**/GoogleService-Info.plist
 
   quickstart_framework_messaging:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -601,17 +609,16 @@ jobs:
       run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart_framework.sh "${SDK}")
     - name: Test Swift Quickstart
       run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart_framework.sh "${SDK}" swift)
-    - name: Remove data before upload
-      if: always()
-      run: scripts/remove_data.sh messaging
-    # - uses: actions/upload-artifact@v4
-    #   if: failure()
-    #   with:
-    #     name: quickstart_artifacts_messaging
-    #     path: quickstart-ios/
+    - uses: actions/upload-artifact@v4
+      if: failure()
+      with:
+        name: quickstart_artifacts_messaging
+        path: |
+          quickstart-ios/
+          !quickstart-ios/**/GoogleService-Info.plist
 
   quickstart_framework_storage:
-    needs: package-head
+    needs: packaging_done
     if: ${{ !cancelled() && (success() || github.event.inputs.zip_run_id != '') }}
     env:
       plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
@@ -653,11 +660,10 @@ jobs:
         quickstart-ios/storage/GoogleService-Info.plist "$plist_secret"
     - name: Test Quickstart
       run: ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart_framework.sh "${SDK}")
-    - name: Remove data before upload
-      if: always()
-      run: scripts/remove_data.sh storage
-    # - uses: actions/upload-artifact@v4
-    #   if: failure()
-    #   with:
-    #     name: quickstart_artifacts_storage
-    #     path: quickstart-ios/
+    - uses: actions/upload-artifact@v4
+      if: failure()
+      with:
+        name: quickstart_artifacts_storage
+        path: |
+          quickstart-ios/
+          !quickstart-ios/**/GoogleService-Info.plist
